### ISSUE TITLE
Course codes with empty tables cause IOOBE

### ISSUE THREAD

**Issue by neallithic64** [neallithic64/Enlist-Help#5]
Certain courses with no class offered will cause a Build Failure due to the encountered `java.lang.IndexOutOfBoundsException`. Sample log given below:
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at c.enlistinghelp.CourseOfferingScraper.dispCOffers(CourseOfferingScraper.java:26)
	at c.enlistinghelp.SomeDriver.main(SomeDriver.java:32)
```

Simply put, the issue comes from mishandling (or lack thereof) of empty arrays. A fix would be to add conditions before printing SectionInfo.

**Comment by neallithic64** [comment]
Commit c248ab51d42b66b5f372bac6aa72376400bb3e63 fixed this issue
